# Generated by Django 2.1.3 on 2018-11-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteAsMarkdown', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markdown',
            new_name='MarkdownModel',
        ),
    ]
